name: Feature Branch CI

on:
  push:
    branches:
      - "feature/**g"

# neuer Linux server wirld hier aufgesetzt und nach abschluss gelöscht
jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B test --file pom.xml